### ISSUE TITLE
BADA

### ISSUE THREAD

**Issue by remonvandenbrandt** [ProfHoekstra/bluesky#129]
When using the BADA performance model, I get the following error

```
Using BADA Perfromance model
Traceback (most recent call last):
  File "BlueSky_qtgl.py", line 113, in <module>
    main_loop()
  File "BlueSky_qtgl.py", line 99, in main_loop
    bs.init()
  File "D:\me\repo\bluesky-master\bluesky\__init__.py", line 24, in init
    from bluesky.traffic import Traffic
  File "D:\me\repo\bluesky-master\bluesky\traffic\__init__.py", line 1, in <module>
    from .traffic import Traffic
  File "D:\me\repo\bluesky-master\bluesky\traffic\traffic.py", line 36, in <module>
    from .performance.legacy.perfbada import PerfBADA as Perf
  File "D:\me\repo\bluesky-master\bluesky\traffic\performance\legacy\perfbada.py", line 13, in <module>
    if not coeff_bada.init(settings.perf_path_bada):
  File "D:\me\repo\bluesky-master\bluesky\traffic\performance\legacy\coeff_bada.py", line 122, in init
    ac.setOPFData(opf_parser.parse(file))
  File "D:\me\repo\bluesky-master\bluesky\tools\fwparser.py", line 62, in parse
    dline = [t(s.strip()) for t, s in zip(dtypes, match.groups())]
  File "D:\me\repo\bluesky-master\bluesky\tools\fwparser.py", line 62, in <listcomp>
    dline = [t(s.strip()) for t, s in zip(dtypes, match.groups())]
ValueError: invalid literal for int() with base 10: ''
Found BADA version 3.6 (release date May 25 2004)
296 aircraft entries loaded
```

Any clue to what could be causing this?

**Comment by jooste** [comment]
Hi Remon,

This is caused by a formatting error in one of your BADA coefficient files. Commit 3d23075 makes the parser more robust against such problems.
