### ISSUE TITLE
BlueSky crashes when loading some scenarios

### ISSUE THREAD

**Issue by RubenJacobse** [ProfHoekstra/bluesky#156]
When opening some scenarios BlueSky freezes and stops responding. 
(Issue observed with: ASAS-01.scn, ASAS-04.scn; but not with i.e.: KLM1705-EHAM-LEMD.scn)   

Following error message appears in console:

Traceback (most recent call last):
  File "C:\... ...\bluesky\bluesky\network\client.py", line 112, in receive
    self.event(eventname, pydata, self.sender_id)
  File "C:\... ...\bluesky\bluesky\ui\qtgl\guiclient.py", line 60, in event
    sender_data.setflag(**data)
TypeError: setflag() missing 1 required positional argument: 'args'

**Comment by jooste** [comment]
Fixed in 9d5a278.
