### ISSUE TITLE
Performance limits fails for multiple aircraft.

### ISSUE THREAD

**Issue by BVonk** [ProfHoekstra/bluesky#173]
Commit bitwise and/or -> logical and/or  gives issues when multiple aircraft are present in simulation

Traceback (most recent call last):
  File "BlueSky.py", line 113, in <module>
    main()
  File "BlueSky.py", line 81, in main
    bs.sim.start()
  File "C:\Users\\Documents\bluesky\bluesky\network\node.py", line 46, in start
    self.run()
  File "C:\Users\t\Documents\bluesky\bluesky\network\node.py", line 69, in run
    self.step()
  File "C:\Users\\Documents\bluesky\bluesky\simulation\qtgl\simulation.py", line 106, in step
    bs.traf.update(self.simt, self.simdt)
  File "C:\Users\\Documents\bluesky\bluesky\traffic\traffic.py", line 381, in update
    self.pilot.applylimits()
  File "C:\Users\\Documents\bluesky\bluesky\traffic\pilot.py", line 71, in applylimits
    bs.traf.perf.limits() # Sets limspd_flag and limspd when it needs to be limited
  File "C:\Users\\Documents\bluesky\bluesky\traffic\performance\legacy\perfbs.py", line 378, in limits
    self.phase)
  File "C:\Users\\Documents\bluesky\bluesky\traffic\performance\legacy\performance.py", line 252, in calclimits
    limvs       = np.where((desvs > 0.) and (gs<to_spd) and (phase == 6), 0.0, limvs)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by jooste** [comment]
reverted in e5193f2.
