### ISSUE TITLE
some scenarios fail to load

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#4]
The following scenarios produce errors:

* `CIRCLE12.SCN`

   ```text
Traceback (most recent call last):
  File "c:\repos\bluesky\bluesky\sim\qtgl\simulation.py", line 79, in doWork
    self.stack.process(self, self.traf, self.screenio)
  File "c:\repos\bluesky\bluesky\stack\stack.py", line 289, in process
    cmd = self.cmdsynon[key]
NameError: global name 'key' is not defined
   ```

* `EHAM-TAXY-SCN`

    ```text
Traceback (most recent call last):
  File "c:\repos\bluesky\bluesky\sim\qtgl\simulation.py", line 82, in doWork
    self.traf.update(self.simt, self.simdt)
  File "c:\repos\bluesky\bluesky\traf\traffic.py", line 554, in update
    self.dbconf.conflictlist(simt)
  File "c:\repos\bluesky\bluesky\traf\asas.py", line 212, in conflictlist
    self.confidxs = np.where(self.swconfl)
AttributeError: Dbconf instance has no attribute 'swconfl'
    ```

* `INTENT.scn`

    ```text
Traceback (most recent call last):
  File "c:\repos\bluesky\bluesky\sim\qtgl\simulation.py", line 79, in doWork
    self.stack.process(self, self.traf, self.screenio)
  File "c:\repos\bluesky\bluesky\stack\stack.py", line 289, in process
    cmd = self.cmdsynon[key]
NameError: global name 'key' is not defined
    ```

* `mtn.scn`

    ```text
Reading scenario file:  C:/repos/bluesky/scenario/mtn.scn

except this:  0:00:00,00>CRE MS841, B737,  51.42972,   4.15673, 118.4 FL320, 400
    ```

* `RUNWAYINCURSION.scn`

    ```text
Traceback (most recent call last):
  File "c:\repos\bluesky\bluesky\sim\qtgl\simulation.py", line 79, in doWork
    self.stack.process(self, self.traf, self.screenio)
  File "c:\repos\bluesky\bluesky\stack\stack.py", line 316, in process
    arglist.append(float(cmdargs[i]))
ValueError: invalid literal for float(): 326.8T
    ```

    and similarly for other similar floats with a trailing `T`

* `Test-1-on-1-90-deg.scn`

    ```text
Reading scenario file:  C:/repos/bluesky/scenario/Test-1-on-1-90-deg.scn

aircraft is using default aircraft performance (Boeing 747-400).
Syntax error in command:  FIXDT ON,20
    ```

* `TESTWP.SCN`

    ```text
Reading scenario file:  C:/repos/bluesky/scenario/TESTWP.SCN

Traceback (most recent call last):
  File "c:\repos\bluesky\bluesky\sim\qtgl\simulation.py", line 79, in doWork
    self.stack.process(self, self.traf, self.screenio)
  File "c:\repos\bluesky\bluesky\stack\stack.py", line 357, in process
    results = function(arglist)
  File "c:\repos\bluesky\bluesky\traf\traffic.py", line 903, in create
    acspd = mach2tas(cmdspd,acalt)
NameError: global name 'mach2tas' is not defined
   ```

* `WALLH.SCN`

    ```text
Reading scenario file:  C:/repos/bluesky/scenario/WALLH.SCN

Traceback (most recent call last):
  File "c:\repos\bluesky\bluesky\sim\qtgl\simulation.py", line 79, in doWork
    self.stack.process(self, self.traf, self.screenio)
  File "c:\repos\bluesky\bluesky\stack\stack.py", line 289, in process
    cmd = self.cmdsynon[key]
NameError: global name 'key' is not defined
    ```

**Comment by jooste** [comment]
Ok, I've checked all the scenario's that you mention, and fixed the bugs. Thanks for letting us know!
If you still have issues with something just let me know.
